version: "3.9"
services:
  game-queue: 
    image: schickling/beanstalkd
    expose: 
      - "11300"
    ports: 
      - "11300:11300"
  campaign-server:
    build: .
    environment: 
      - SUPABASE_SECRET_KEY
      - DROPLET_IP
    depends_on:
      - game-queue